// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzzLNqzIMEuVtllkRcKfsauGMGDRIuWZo',
    appId: '1:323732952127:web:53aea63221f403d5e6d48a',
    messagingSenderId: '323732952127',
    projectId: 'greenhouse-ai-fancontroller',
    authDomain: 'greenhouse-ai-fancontroller.firebaseapp.com',
    databaseURL: 'https://greenhouse-ai-fancontroller-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'greenhouse-ai-fancontroller.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu_wOR83yUH3uT4qjJIqShs3Bz3-Xydvk',
    appId: '1:323732952127:android:d03901d48b0abc43e6d48a',
    messagingSenderId: '323732952127',
    projectId: 'greenhouse-ai-fancontroller',
    databaseURL: 'https://greenhouse-ai-fancontroller-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'greenhouse-ai-fancontroller.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9y5SNWVSd88iOP0hGdqWiSQAwcZzmnno',
    appId: '1:323732952127:ios:1ae85403eb97d863e6d48a',
    messagingSenderId: '323732952127',
    projectId: 'greenhouse-ai-fancontroller',
    databaseURL: 'https://greenhouse-ai-fancontroller-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'greenhouse-ai-fancontroller.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9y5SNWVSd88iOP0hGdqWiSQAwcZzmnno',
    appId: '1:323732952127:ios:1ae85403eb97d863e6d48a',
    messagingSenderId: '323732952127',
    projectId: 'greenhouse-ai-fancontroller',
    databaseURL: 'https://greenhouse-ai-fancontroller-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'greenhouse-ai-fancontroller.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzzLNqzIMEuVtllkRcKfsauGMGDRIuWZo',
    appId: '1:323732952127:web:aeb19e9432f858eee6d48a',
    messagingSenderId: '323732952127',
    projectId: 'greenhouse-ai-fancontroller',
    authDomain: 'greenhouse-ai-fancontroller.firebaseapp.com',
    databaseURL: 'https://greenhouse-ai-fancontroller-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'greenhouse-ai-fancontroller.firebasestorage.app',
  );
}
